[package]
name="conway"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js", "boogie"]

[build.whiley]
verify=false

[build.js]
target="public/js"

[build.boogie]
timeout=30
verify=false

[check]
min=-1
max=1
length=3
ignores=["main::draw"]

[dependencies]
dom="0.2.0"
