[package]
name="conway"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js"]

[build.whiley]
source="src/whiley"
verify=false

[check]
min=-4
max=4
length=4
ignores=["main::draw"]

[dependencies]
html="0.1.10"
