[package]
name="conway"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","js"]

[build.js]
target="public/js"

[check]
min=-1
max=1
length=3
ignores=["main::draw"]

[dependencies]
dom="0.2.2"
js="0.1.7"
std="0.3.2"
